"""add_user_tracking_columns

Revision ID: 15855720e320
Revises: 78a01fbcbc36
Create Date: 2025-10-25 18:03:27.823781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15855720e320'
down_revision = '78a01fbcbc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terms_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('privacy_policy_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('privacy_policy_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('marketing_emails', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('marketing_emails_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_orders', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_spent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_order_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_order_date')
        batch_op.drop_column('total_spent')
        batch_op.drop_column('total_orders')
        batch_op.drop_column('login_count')
        batch_op.drop_column('marketing_emails_accepted_at')
        batch_op.drop_column('marketing_emails')
        batch_op.drop_column('privacy_policy_accepted_at')
        batch_op.drop_column('privacy_policy_accepted')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('terms_accepted')

    # ### end Alembic commands ###
