"""Agregar campos detalles producto, multimedia y sistema de reseñas

Revision ID: 9625875a7203
Revises: da47f15bec84
Create Date: 2025-10-16 18:35:12.964609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9625875a7203'
down_revision = 'da47f15bec84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videos', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('material', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cuidados', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('origen', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('disponibilidad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('costo_prenda', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('costo_prenda')
        batch_op.drop_column('disponibilidad')
        batch_op.drop_column('origen')
        batch_op.drop_column('cuidados')
        batch_op.drop_column('material')
        batch_op.drop_column('videos')

    op.drop_table('reviews')
    # ### end Alembic commands ###
