"""empty message

Revision ID: e1cdd643e179
Revises: 335a5b0082b7
Create Date: 2025-11-15 12:04:01.634745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cdd643e179'
down_revision = '335a5b0082b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_address_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'user_addresses', ['user_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_address_id')

    # ### end Alembic commands ###
